# Association Rule Learning (Apriori Algorithm) - ARL
- Association rule learning involves identifying strong associations between different items in a dataset.

- A rule is defined as an implication: if item A is purchased, then item B is likely to be purchased.

#### Apriori Algorithm Steps:
1. Data Preparation:
    - Collect a dataset of transactions, where each transaction is a set of items.

    - Convert the dataset into a suitable format, such as a binary matrix or a transaction database.

2. Generate Frequent Itemsets:
    - Identify the most frequent itemsets in the dataset using a suitable algorithm, such as Apriori.

    - Frequent itemsets are those that appear in at least a certain number of transactions.

#### Types of Association Rule Learning Algorithms:
1. Apriori:
    - Iteratively identifies frequent itemsets using a bottom-up approach.

    - Filters combinations based on minimum support and generates rules with confidence thresholds.

    - Example: In a grocery store, Apriori identifies that people buying bread often buy butter.

2. Eclat (Equivalence Class Clustering and Bottom-up Lattice Traversal):
    - Uses a depth-first search approach with vertical dataset representation.

    - Faster than Apriori for large datasets.

    - Example: Eclat quickly identifies frequent patterns like {milk, cereal} in sales data.

3. FP-Growth (Frequent Pattern Growth):
    - Constructs a compact tree structure (FP-tree) for storing itemsets.

    - Avoids candidate generation like Apriori.
    
    - Example: FP-Growth detects patterns like {diapers, beer} in sales efficiently.

## Importing the necessary libraries

In [28]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set_theme()

## Loading the dataset

In [29]:
dataset = pd.read_csv('Market_Basket_Optimisation.csv', header = None) # The 'header = None' indicates no column names.
dataset

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,shrimp,almonds,avocado,vegetables mix,green grapes,whole weat flour,yams,cottage cheese,energy drink,tomato juice,low fat yogurt,green tea,honey,salad,mineral water,salmon,antioxydant juice,frozen smoothie,spinach,olive oil
1,burgers,meatballs,eggs,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,chutney,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,turkey,avocado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,mineral water,milk,energy bar,whole wheat rice,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7496,butter,light mayo,fresh bread,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7497,burgers,frozen vegetables,eggs,french fries,magazines,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7498,chicken,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7499,escalope,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7500,eggs,frozen smoothie,yogurt cake,low fat yogurt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Data Preprocessing

In [30]:
transactions = []
for i in range(0, dataset.shape[0]):
  temp = [str(dataset.values[i,j]) for j in range(0, dataset.shape[1])] # 'i = row index', 'j = column index'
  temp = sorted(list(set(temp)))
  transactions.append(temp)

In [31]:
transactions

[['almonds',
  'antioxydant juice',
  'avocado',
  'cottage cheese',
  'energy drink',
  'frozen smoothie',
  'green grapes',
  'green tea',
  'honey',
  'low fat yogurt',
  'mineral water',
  'olive oil',
  'salad',
  'salmon',
  'shrimp',
  'spinach',
  'tomato juice',
  'vegetables mix',
  'whole weat flour',
  'yams'],
 ['burgers', 'eggs', 'meatballs', 'nan'],
 ['chutney', 'nan'],
 ['avocado', 'nan', 'turkey'],
 ['energy bar',
  'green tea',
  'milk',
  'mineral water',
  'nan',
  'whole wheat rice'],
 ['low fat yogurt', 'nan'],
 ['french fries', 'nan', 'whole wheat pasta'],
 ['light cream', 'nan', 'shallot', 'soup'],
 ['frozen vegetables', 'green tea', 'nan', 'spaghetti'],
 ['french fries', 'nan'],
 ['eggs', 'nan', 'pet food'],
 ['cookies', 'nan'],
 ['burgers', 'cooking oil', 'eggs', 'mineral water', 'nan', 'turkey'],
 ['champagne', 'cookies', 'nan', 'spaghetti'],
 ['mineral water', 'nan', 'salmon'],
 ['mineral water', 'nan'],
 ['chicken',
  'chocolate',
  'cooking oil',
  'honey',
  'low fat yogurt',
  'nan',
  'oil',
  'shrimp'],
 ['eggs', 'nan', 'turkey'],
 ['black tea',
  'chicken',
  'eggs',
  'extra dark chocolate',
  'fresh tuna',
  'mineral water',
  'nan',
  'salmon',
  'spaghetti',
  'tomatoes',
  'turkey'],
 ['french fries', 'honey', 'meatballs', 'milk', 'nan', 'protein bar'],
 ['chocolate',
  'eggs',
  'nan',
  'pasta',
  'pepper',
  'red wine',
  'shampoo',
  'shrimp'],
 ['nan', 'rice', 'sparkling water'],
 ['body spray',
  'green tea',
  'ham',
  'mineral water',
  'nan',
  'pancakes',
  'spaghetti'],
 ['avocado',
  'burgers',
  'grated cheese',
  'honey',
  'nan',
  'pasta',
  'shrimp',
  'toothpaste',
  'white wine'],
 ['eggs', 'nan'],
 ['avocado',
  'fresh bread',
  'milk',
  'nan',
  'parmesan cheese',
  'soup',
  'spaghetti'],
 ['black tea',
  'energy bar',
  'escalope',
  'frozen smoothie',
  'ground beef',
  'milk',
  'mineral water',
  'nan',
  'salmon',
  'spaghetti'],
 ['nan', 'sparkling water'],
 ['chicken', 'chocolate', 'eggs', 'french fries', 'mineral water', 'nan'],
 ['frozen vegetables', 'mineral water', 'nan', 'spaghetti', 'yams'],
 ['herb & pepper', 'light cream', 'magazines', 'nan', 'tomato sauce'],
 ['avocado', 'chocolate', 'eggs', 'mineral water', 'nan'],
 ['french fries', 'nan', 'strawberries', 'turkey'],
 ['chocolate', 'frozen vegetables', 'nan', 'strong cheese'],
 ['cookies', 'nan'],
 ['escalope', 'nan', 'pickles', 'salmon', 'spaghetti'],
 ['energy bar', 'french fries', 'nan'],
 ['ground beef', 'mineral water', 'nan', 'red wine'],
 ['cake', 'cottage cheese', 'mineral water', 'nan'],
 ['champagne', 'green tea', 'nan', 'pickles'],
 ['nan', 'spaghetti'],
 ['escalope',
  'fresh tuna',
  'frozen smoothie',
  'frozen vegetables',
  'honey',
  'mineral water',
  'nan',
  'spaghetti',
  'whole wheat rice'],
 ['nan', 'spaghetti'],
 ['hot dogs', 'meatballs', 'nan', 'soup', 'sparkling water'],
 ['escalope', 'nan'],
 ['avocado',
  'body spray',
  'brownies',
  'french fries',
  'green tea',
  'hot dogs',
  'nan',
  'pancakes',
  'soup'],
 ['cereals', 'chicken', 'clothes accessories', 'mineral water', 'nan'],
 ['bug spray', 'mineral water', 'nan'],
 ['avocado', 'muffins', 'nan'],
 ['black tea', 'burgers', 'green tea', 'nan'],
 ['brownies', 'chocolate', 'green tea', 'nan', 'spaghetti', 'white wine'],
 ['eggs', 'fresh tuna', 'mineral water', 'nan'],
 ['muffins', 'nan', 'spaghetti'],
 ['chocolate', 'nan', 'spaghetti'],
 ['champagne', 'escalope', 'french fries', 'nan'],
 ['light mayo', 'nan', 'tomato sauce'],
 ['chocolate',
  'fresh tuna',
  'frozen vegetables',
  'ground beef',
  'milk',
  'mineral water',
  'nan',
  'olive oil',
  'soup',
  'spaghetti',
  'tomatoes',
  'turkey'],
 ['cookies', 'eggs', 'nan'],
 ['body spray',
  'chicken',
  'energy drink',
  'green tea',
  'gums',
  'nan',
  'soda',
  'soup'],
 ['cider',
  'cooking oil',
  'frozen vegetables',
  'green tea',
  'mineral water',
  'nan',
  'turkey'],
 ['nan', 'spaghetti'],
 ['clothes accessories', 'nan'],
 ['energy drink', 'nan'],
 ['bug spray', 'green tea', 'nan', 'protein bar', 'shallot', 'soup'],
 ['eggs', 'nan', 'turkey'],
 ['french fries', 'nan'],
 ['chocolate', 'milk', 'nan'],
 ['avocado',
  'cider',
  'ground beef',
  'herb & pepper',
  'mineral water',
  'nan',
  'whole wheat pasta',
  'whole wheat rice'],
 ['cookies', 'nan'],
 ['nan', 'pasta', 'shrimp'],
 ['corn', 'grated cheese', 'herb & pepper', 'nan', 'tomato sauce', 'tomatoes'],
 ['burgers', 'escalope', 'nan', 'shallot'],
 ['cookies', 'nan'],
 ['nan', 'yogurt cake'],
 ['eggs', 'nan', 'soup'],
 ['cookies', 'nan'],
 ['chocolate', 'low fat yogurt', 'mineral water', 'nan'],
 ['eggs', 'nan', 'strawberries'],
 ['grated cheese',
  'ground beef',
  'mineral water',
  'nan',
  'spaghetti',
  'white wine'],
 ['mint', 'nan'],
 ['cake', 'eggs', 'french fries', 'nan'],
 ['burgers', 'french fries', 'green tea', 'milk', 'nan', 'spaghetti'],
 ['butter', 'energy bar', 'french fries', 'mineral water', 'nan'],
 ['burgers',
  'cooking oil',
  'eggs',
  'grated cheese',
  'herb & pepper',
  'mineral water',
  'nan'],
 ['energy bar', 'nan'],
 ['energy bar', 'energy drink', 'nan'],
 ['chocolate', 'frozen smoothie', 'nan'],
 ['low fat yogurt', 'nan'],
 ['asparagus', 'nan', 'salad'],
 ['burgers', 'french fries', 'green tea', 'low fat yogurt', 'nan'],
 ['low fat yogurt', 'nan'],
 ['burgers',
  'eggs',
  'energy bar',
  'french wine',
  'herb & pepper',
  'meatballs',
  'mineral water',
  'nan',
  'olive oil',
  'pasta',
  'salt',
  'shrimp',
  'spaghetti'],
 ['champagne', 'low fat yogurt', 'nan'],
 ['champagne', 'nan'],
 ['almonds', 'burgers', 'cookies', 'eggs', 'french fries', 'green tea', 'nan'],
 ['body spray', 'escalope', 'ham', 'nan', 'soup'],
 ['extra dark chocolate',
  'frozen vegetables',
  'ham',
  'magazines',
  'nan',
  'oil',
  'pepper',
  'tea',
  'turkey'],
 ['cookies', 'eggs', 'muffins', 'nan'],
 ['cookies', 'nan'],
 ['chocolate',
  'frozen vegetables',
  'green tea',
  'ground beef',
  'nan',
  'spaghetti',
  'whole wheat pasta'],
 ['barbecue sauce', 'chocolate', 'mineral water', 'nan'],
 ['almonds',
  'burgers',
  'corn',
  'eggs',
  'energy bar',
  'herb & pepper',
  'mayonnaise',
  'nan',
  'zucchini'],
 ['almonds',
  'burgers',
  'chocolate',
  'cottage cheese',
  'eggs',
  'ground beef',
  'hot dogs',
  'nan',
  'soup',
  'turkey'],
 ['chocolate', 'eggs', 'ham', 'nan', 'spaghetti'],
 ['carrots', 'energy bar', 'ground beef', 'nan', 'pet food', 'protein bar'],
 ['almonds',
  'eggs',
  'ground beef',
  'mineral water',
  'nan',
  'spaghetti',
  'tomato sauce'],
 ['cooking oil', 'gums', 'mineral water', 'nan', 'olive oil'],
 ['avocado',
  'bug spray',
  'eggs',
  'green grapes',
  'milk',
  'mineral water',
  'nan',
  'olive oil',
  'pasta',
  'shrimp',
  'soup'],
 ['cake',
  'chicken',
  'cooking oil',
  'light mayo',
  'low fat yogurt',
  'nan',
  'pasta',
  'shrimp',
  'soup'],
 ['champagne',
  'chocolate',
  'escalope',
  'french fries',
  'fresh bread',
  'mineral water',
  'mushroom cream sauce',
  'nan',
  'spaghetti'],
 ['eggs', 'mineral water', 'nan', 'pasta', 'shrimp'],
 ['burgers', 'fresh bread', 'nan', 'oil', 'tomato juice'],
 ['chocolate', 'eggs', 'french wine', 'low fat yogurt', 'nan'],
 ['chicken', 'eggs', 'french fries', 'nan', 'pancakes'],
 ['candy bars', 'herb & pepper', 'nan', 'salmon', 'turkey', 'white wine'],
 ['eggs',
  'french fries',
  'grated cheese',
  'green tea',
  'nan',
  'olive oil',
  'spaghetti'],
 ['energy bar', 'mineral water', 'nan'],
 ['eggs', 'french fries', 'nan'],
 ['almonds',
  'burgers',
  'chocolate',
  'eggs',
  'milk',
  'mineral water',
  'nan',
  'soup',
  'tomato juice',
  'tomatoes'],
 ['muffins', 'nan'],
 ['nan', 'pasta'],
 ['frozen smoothie', 'nan', 'spaghetti', 'tomatoes'],
 ['ground beef', 'milk', 'nan', 'spaghetti'],
 ['french fries', 'nan'],
 ['chocolate', 'milk', 'nan'],
 ['burgers',
  'chocolate',
  'eggs',
  'french fries',
  'frozen vegetables',
  'low fat yogurt',
  'milk',
  'mineral water',
  'nan',
  'pancakes',
  'pasta',
  'shrimp',
  'spaghetti'],
 ['antioxydant juice', 'ground beef', 'mineral water', 'nan', 'protein bar'],
 ['cake',
  'energy drink',
  'grated cheese',
  'ground beef',
  'nan',
  'spaghetti',
  'whole wheat pasta'],
 ['grated cheese', 'nan'],
 ['nan', 'pancakes'],
 ['frozen smoothie', 'nan'],
 ['carrots', 'green tea', 'nan'],
 ['chocolate', 'nan'],
 ['burgers',
  'chocolate',
  'cooking oil',
  'corn',
  'eggs',
  'nan',
  'olive oil',
  'turkey'],
 ['chicken',
  'chili',
  'french fries',
  'fresh bread',
  'frozen vegetables',
  'mineral water',
  'nan',
  'pancakes',
  'pepper',
  'spaghetti',
  'tea',
  'tomato juice',
  'tomatoes'],
 ['cookies', 'nan'],
 ['ground beef', 'nan'],
 ['chocolate', 'eggs', 'frozen smoothie', 'nan', 'tomato juice', 'turkey'],
 ['cooking oil', 'frozen vegetables', 'mashed potato', 'nan'],
 ['frozen vegetables',
  'ground beef',
  'light cream',
  'meatballs',
  'mineral water',
  'nan',
  'olive oil',
  'tomato juice',
  'tomato sauce'],
 ['cake',
  'chocolate',
  'cooking oil',
  'eggs',
  'frozen smoothie',
  'gums',
  'milk',
  'mineral water',
  'nan',
  'red wine',
  'soup',
  'spaghetti'],
 ['avocado',
  'brownies',
  'chocolate',
  'eggs',
  'french fries',
  'milk',
  'mineral water',
  'nan',
  'olive oil',
  'rice',
  'spaghetti',
  'tomatoes'],
 ['chocolate',
  'eggs',
  'frozen vegetables',
  'ground beef',
  'mineral water',
  'nan',
  'nonfat milk',
  'pasta',
  'shrimp'],
 ['chicken',
  'eggs',
  'french fries',
  'mineral water',
  'nan',
  'pasta',
  'pepper',
  'shrimp',
  'spaghetti',
  'turkey'],
 ['cookies', 'nan'],
 ['cake', 'nan', 'tomatoes', 'turkey'],
 ['barbecue sauce',
  'carrots',
  'champagne',
  'chocolate',
  'milk',
  'mineral water',
  'nan',
  'pancakes',
  'soup',
  'whole wheat rice',
  'yams'],
 ['nan', 'rice'],
 ['chocolate', 'milk', 'nan'],
 ['frozen vegetables', 'nan', 'pasta', 'shrimp', 'water spray'],
 ['burgers',
  'eggs',
  'milk',
  'mineral water',
  'mint',
  'nan',
  'whole wheat rice'],
 ['brownies',
  'cake',
  'frozen smoothie',
  'mineral water',
  'nan',
  'vegetables mix'],
 ['cookies', 'nan'],
 ['chicken', 'chocolate bread', 'nan', 'pasta', 'shrimp'],
 ['nan', 'shallot'],
 ['eggs', 'green tea', 'hot dogs', 'nan', 'pasta', 'shrimp', 'spaghetti'],
 ['burgers', 'nan'],
 ['cooking oil',
  'ground beef',
  'light cream',
  'milk',
  'mineral water',
  'nan',
  'olive oil',
  'red wine',
  'spaghetti',
  'strong cheese'],
 ['avocado',
  'burgers',
  'french fries',
  'grated cheese',
  'milk',
  'nan',
  'oil',
  'spaghetti'],
 ['ground beef',
  'herb & pepper',
  'mineral water',
  'nan',
  'olive oil',
  'whole wheat pasta'],
 ['chocolate', 'milk', 'nan', 'pasta', 'shrimp', 'yams'],
 ['butter', 'green tea', 'nan'],
 ['light mayo', 'nan'],
 ['low fat yogurt', 'nan'],
 ['herb & pepper', 'milk', 'nan', 'pasta', 'shrimp', 'spaghetti'],
 ['burgers', 'eggs', 'nan'],
 ['avocado',
  'barbecue sauce',
  'black tea',
  'carrots',
  'cookies',
  'eggs',
  'fresh bread',
  'ground beef',
  'herb & pepper',
  'milk',
  'nan',
  'soup',
  'tomato juice',
  'turkey'],
 ['cookies', 'nan'],
 ['escalope', 'nan'],
 ['french fries',
  'low fat yogurt',
  'nan',
  'pancakes',
  'pepper',
  'strawberries'],
 ['chicken', 'frozen vegetables', 'honey', 'light mayo', 'nan', 'yams'],
 ['champagne', 'chocolate', 'nan'],
 ['cake', 'herb & pepper', 'honey', 'nan', 'protein bar', 'rice'],
 ['asparagus',
  'burgers',
  'chocolate',
  'frozen vegetables',
  'ground beef',
  'light mayo',
  'milk',
  'mineral water',
  'nan'],
 ['chocolate', 'corn', 'cottage cheese', 'green tea', 'mineral water', 'nan'],
 ['muffins', 'nan'],
 ['escalope', 'french wine', 'ham', 'nan'],
 ['milk', 'mint green tea', 'nan', 'spaghetti', 'whole wheat rice'],
 ['body spray', 'chocolate', 'nan'],
 ['french fries', 'frozen vegetables', 'hot dogs', 'nan'],
 ['candy bars', 'nan'],
 ['burgers',
  'cookies',
  'french fries',
  'green tea',
  'milk',
  'nan',
  'pasta',
  'shrimp',
  'white wine'],
 ['ground beef', 'nan', 'parmesan cheese'],
 ['candy bars', 'nan', 'pancakes', 'whole wheat rice'],
 ['cookies', 'eggplant', 'eggs', 'nan'],
 ['frozen vegetables', 'mineral water', 'nan'],
 ['chocolate', 'nan'],
 ['chocolate', 'milk', 'nan', 'spaghetti', 'turkey', 'whole wheat rice'],
 ['blueberries',
  'champagne',
  'chicken',
  'cooking oil',
  'ground beef',
  'meatballs',
  'nan',
  'protein bar',
  'soup',
  'spaghetti',
  'whole wheat pasta',
  'yogurt cake'],
 ['cooking oil', 'nan', 'tomato juice'],
 ['eggs', 'french fries', 'frozen vegetables', 'green tea', 'milk', 'nan'],
 ['champagne',
  'eggs',
  'french fries',
  'french wine',
  'fresh tuna',
  'light mayo',
  'nan',
  'olive oil',
  'pancakes',
  'spaghetti'],
 ['honey', 'hot dogs', 'nan', 'red wine'],
 ['bacon', 'eggs', 'french fries', 'fresh bread', 'milk', 'nan'],
 ['french fries', 'nan', 'yogurt cake'],
 ['milk', 'nan'],
 ['french fries', 'nan'],
 ['chocolate', 'nan'],
 ['burgers', 'ham', 'nan', 'red wine'],
 ['antioxydant juice',
  'brownies',
  'energy bar',
  'french fries',
  'french wine',
  'frozen smoothie',
  'nan',
  'pasta',
  'shrimp',
  'tomatoes'],
 ['green tea', 'nan'],
 ['low fat yogurt', 'nan'],
 ['energy drink',
  'mineral water',
  'nan',
  'salt',
  'soda',
  'soup',
  'spaghetti',
  'spinach',
  'turkey'],
 ['eggs', 'nan', 'turkey'],
 ['bug spray', 'hot dogs', 'nan'],
 ['nan', 'oil'],
 ['body spray',
  'cake',
  'chicken',
  'eggs',
  'energy bar',
  'french fries',
  'nan',
  'soup',
  'strawberries'],
 ['chocolate', 'nan', 'spaghetti', 'yogurt cake'],
 ['meatballs', 'mineral water', 'nan', 'turkey'],
 ['bacon',
  'chocolate',
  'fromage blanc',
  'ground beef',
  'hot dogs',
  'mineral water',
  'nan'],
 ['escalope', 'frozen vegetables', 'mineral water', 'nan', 'vegetables mix'],
 ['herb & pepper', 'nan', 'red wine', 'tomatoes'],
 ['brownies', 'cereals', 'green tea', 'nan', 'olive oil', 'whole wheat pasta'],
 ['cookies', 'nan'],
 ['cookies', 'mushroom cream sauce', 'nan', 'olive oil'],
 ['cooking oil',
  'gluten free bar',
  'ground beef',
  'light mayo',
  'nan',
  'pancakes'],
 ['french fries', 'mineral water', 'nan'],
 ['herb & pepper', 'nan'],
 ['nan', 'salmon'],
 ['eggs', 'escalope', 'nan'],
 ['mineral water', 'nan', 'tomato juice'],
 ['mineral water', 'nan'],
 ['black tea', 'mineral water', 'nan', 'shrimp', 'soup'],
 ['cake', 'frozen smoothie', 'nan'],
 ['burgers',
  'chocolate',
  'fromage blanc',
  'grated cheese',
  'honey',
  'nan',
  'tomatoes',
  'turkey',
  'whole wheat rice'],
 ['frozen vegetables',
  'ground beef',
  'mineral water',
  'nan',
  'olive oil',
  'pancakes'],
 ['burgers',
  'cake',
  'fresh bread',
  'ground beef',
  'milk',
  'nan',
  'olive oil',
  'turkey'],
 ['cereals',
  'chutney',
  'energy drink',
  'ground beef',
  'mineral water',
  'nan',
  'protein bar',
  'soup',
  'spaghetti',
  'whole wheat pasta',
  'yams'],
 ['cake', 'eggs', 'escalope', 'green tea', 'nan', 'whole wheat rice'],
 ['avocado', 'green tea', 'ground beef', 'nan', 'salmon', 'soup', 'yams'],
 ['milk', 'nan'],
 ['chocolate', 'nan', 'spaghetti'],
 ['honey', 'nan', 'whole wheat pasta'],
 ['green tea', 'nan', 'whole wheat pasta'],
 ['chocolate', 'meatballs', 'nan', 'spaghetti', 'vegetables mix'],
 ['eggs', 'low fat yogurt', 'nan'],
 ['brownies',
  'cake',
  'eggs',
  'fresh tuna',
  'mineral water',
  'nan',
  'olive oil',
  'pasta',
  'shrimp',
  'tomato juice'],
 ['fresh bread', 'green grapes', 'hot dogs', 'mineral water', 'nan'],
 ['chocolate', 'eggs', 'frozen vegetables', 'meatballs', 'nan'],
 ['chocolate', 'nan'],
 ['meatballs', 'milk', 'nan'],
 ['low fat yogurt', 'nan'],
 ['green tea', 'nan'],
 ['escalope', 'nan', 'pasta'],
 ['chocolate',
  'french wine',
  'fresh bread',
  'light mayo',
  'magazines',
  'nan',
  'olive oil',
  'pepper',
  'rice',
  'salmon'],
 ['clothes accessories',
  'french wine',
  'green tea',
  'hot dogs',
  'nan',
  'red wine',
  'rice',
  'vegetables mix'],
 ['burgers',
  'cake',
  'chicken',
  'dessert wine',
  'green tea',
  'nan',
  'protein bar',
  'spaghetti'],
 ['cake', 'french wine', 'fresh bread', 'nan'],
 ['burgers', 'eggs', 'flax seed', 'frozen vegetables', 'nan'],
 ['nan', 'red wine'],
 ['energy bar', 'green grapes', 'mineral water', 'nan', 'pepper'],
 ['cake', 'chocolate', 'eggs', 'french fries', 'green tea', 'milk', 'nan'],
 ['french fries', 'nan'],
 ['almonds', 'nan'],
 ['burgers', 'green tea', 'mineral water', 'nan'],
 ['milk', 'nan', 'pancakes'],
 ['eggs', 'nan', 'pancakes', 'salt', 'tomato juice'],
 ['mineral water', 'nan'],
 ['ham', 'mineral water', 'nan', 'olive oil', 'spaghetti'],
 ['fresh bread', 'nan', 'salt', 'tomato juice'],
 ['mushroom cream sauce', 'nan', 'spaghetti'],
 ['eggs', 'mineral water', 'nan', 'pet food', 'spaghetti'],
 ['frozen vegetables', 'nan', 'spaghetti'],
 ['energy drink', 'nan'],
 ['muffins', 'nan'],
 ['milk', 'nan', 'turkey'],
 ['cookies', 'nan'],
 ['chocolate', 'nan'],
 ['chocolate',
  'cooking oil',
  'eggs',
  'escalope',
  'mineral water',
  'nan',
  'spaghetti'],
 ['frozen vegetables', 'green tea', 'nan', 'pepper', 'shrimp', 'spaghetti'],
 ['burgers',
  'french fries',
  'fresh tuna',
  'hand protein bar',
  'low fat yogurt',
  'mineral water',
  'nan',
  'red wine'],
 ['eggs', 'energy drink', 'fresh bread', 'nan', 'pancakes'],
 ['french fries',
  'frozen smoothie',
  'green tea',
  'hot dogs',
  'nan',
  'salmon',
  'strong cheese'],
 ['frozen smoothie',
  'grated cheese',
  'milk',
  'nan',
  'pasta',
  'sandwich',
  'shrimp',
  'tomatoes'],
 ['eggs',
  'herb & pepper',
  'nan',
  'olive oil',
  'pancakes',
  'whole wheat pasta'],
 ['antioxydant juice', 'nan', 'spaghetti'],
 ['almonds', 'chocolate', 'eggs', 'milk', 'nan', 'strawberries', 'white wine'],
 ['french fries', 'nan', 'strawberries'],
 ['mineral water', 'nan'],
 ['eggs', 'nan'],
 ['escalope', 'nan'],
 ['cake', 'nan'],
 ['antioxydant juice', 'body spray', 'green tea', 'nan', 'whole wheat pasta'],
 ['frozen smoothie', 'mineral water', 'nan', 'oil'],
 ['champagne', 'french fries', 'nan'],
 ['chocolate', 'french fries', 'nan'],
 ['eggs', 'frozen vegetables', 'nan', 'spaghetti'],
 ['hot dogs', 'nan'],
 ['chocolate', 'cookies', 'nan'],
 ['nan', 'pancakes'],
 ['butter', 'chicken', 'nan', 'salmon', 'shrimp'],
 ['babies food', 'chocolate', 'cookies', 'nan'],
 ['cake',
  'chocolate',
  'french fries',
  'fresh bread',
  'nan',
  'pepper',
  'spaghetti'],
 ['avocado', 'cereals', 'french fries', 'nan', 'oil'],
 ['cooking oil',
  'eggs',
  'green tea',
  'herb & pepper',
  'low fat yogurt',
  'mineral water',
  'nan',
  'oil',
  'shampoo',
  'spaghetti',
  'spinach',
  'tomato juice'],
 ['french fries',
  'frozen vegetables',
  'ground beef',
  'herb & pepper',
  'mint green tea',
  'nan',
  'pepper',
  'spaghetti'],
 ['french fries', 'nan'],
 ['green tea', 'nan', 'tomato juice'],
 ['chocolate', 'eggs', 'nan', 'whole wheat rice'],
 ['cooking oil',
  'eggs',
  'grated cheese',
  'green tea',
  'herb & pepper',
  'mineral water',
  'nan',
  'red wine',
  'salmon',
  'spaghetti'],
 ['cookies',
  'french fries',
  'fresh bread',
  'low fat yogurt',
  'nan',
  'shallot',
  'tomato juice'],
 ['burgers', 'fresh tuna', 'honey', 'muffins', 'nan', 'spaghetti'],
 ['chicken', 'eggs', 'ground beef', 'herb & pepper', 'nan', 'spaghetti'],
 ['grated cheese', 'mayonnaise', 'muffins', 'nan', 'tomato juice'],
 ['energy drink',
  'frozen smoothie',
  'hot dogs',
  'mineral water',
  'muffins',
  'nan',
  'whole wheat pasta',
  'yams'],
 ['blueberries',
  'burgers',
  'eggs',
  'milk',
  'nan',
  'olive oil',
  'salmon',
  'soup',
  'spaghetti'],
 ['champagne', 'chocolate', 'magazines', 'nan'],
 ['chocolate',
  'french wine',
  'frozen vegetables',
  'green grapes',
  'mineral water',
  'nan',
  'rice',
  'spaghetti',
  'yams'],
 ['chocolate', 'nan', 'tomato sauce'],
 ['eggs', 'milk', 'nan'],
 ['nan', 'pet food'],
 ['nan', 'yogurt cake'],
 ['green tea', 'nan'],
 ['escalope', 'nan', 'pasta'],
 ['ground beef', 'herb & pepper', 'nan'],
 ['brownies', 'honey', 'mineral water', 'nan'],

## Training the Apriori model on the dataset

In [32]:
from apyori import apriori

# Training the Apriori model on the dataset
rules = apriori(transactions = transactions, 
                min_support = 0.003, 
                min_confidence = 0.2, 
                min_lift = 3, 
                min_length = 2, 
                max_length = 2)

## Visualising the Results

## Dsiplaying the first results

In [33]:
# Displaying the rules in a readable format
# Putting the results well organised into a Pandas DataFrame
results = list(rules)
results

[RelationRecord(items=frozenset({'chicken', 'light cream'}), support=0.004532728969470737, ordered_statistics=[OrderedStatistic(items_base=frozenset({'light cream'}), items_add=frozenset({'chicken'}), confidence=0.29059829059829057, lift=4.84395061728395)]),
 RelationRecord(items=frozenset({'mushroom cream sauce', 'escalope'}), support=0.005732568990801226, ordered_statistics=[OrderedStatistic(items_base=frozenset({'mushroom cream sauce'}), items_add=frozenset({'escalope'}), confidence=0.3006993006993007, lift=3.790832696715049)]),
 RelationRecord(items=frozenset({'pasta', 'escalope'}), support=0.005865884548726837, ordered_statistics=[OrderedStatistic(items_base=frozenset({'pasta'}), items_add=frozenset({'escalope'}), confidence=0.3728813559322034, lift=4.700811850163794)]),
 RelationRecord(items=frozenset({'honey', 'fromage blanc'}), support=0.003332888948140248, ordered_statistics=[OrderedStatistic(items_base=frozenset({'fromage blanc'}), items_add=frozenset({'honey'}), confidence=0.2450980392156863, lift=5.164270764485569)]),
 RelationRecord(items=frozenset({'herb & pepper', 'ground beef'}), support=0.015997866951073192, ordered_statistics=[OrderedStatistic(items_base=frozenset({'herb & pepper'}), items_add=frozenset({'ground beef'}), confidence=0.3234501347708895, lift=3.2919938411349285)]),
 RelationRecord(items=frozenset({'tomato sauce', 'ground beef'}), support=0.005332622317024397, ordered_statistics=[OrderedStatistic(items_base=frozenset({'tomato sauce'}), items_add=frozenset({'ground beef'}), confidence=0.3773584905660377, lift=3.840659481324083)]),
 RelationRecord(items=frozenset({'light cream', 'olive oil'}), support=0.003199573390214638, ordered_statistics=[OrderedStatistic(items_base=frozenset({'light cream'}), items_add=frozenset({'olive oil'}), confidence=0.20512820512820515, lift=3.1147098515519573)]),
 RelationRecord(items=frozenset({'whole wheat pasta', 'olive oil'}), support=0.007998933475536596, ordered_statistics=[OrderedStatistic(items_base=frozenset({'whole wheat pasta'}), items_add=frozenset({'olive oil'}), confidence=0.2714932126696833, lift=4.122410097642296)]),
 RelationRecord(items=frozenset({'pasta', 'shrimp'}), support=0.005065991201173177, ordered_statistics=[OrderedStatistic(items_base=frozenset({'pasta'}), items_add=frozenset({'shrimp'}), confidence=0.3220338983050847, lift=4.506672147735896)])]

## Putting the results well organised into a Pandas DataFrame

In [64]:
def inspect(results):
    left_hand_side_of_rule  = [tuple(result[2][0][0])[0] for result in results]
    right_hand_side_of_rule = [tuple(result[2][0][1])[0] for result in results]
    supports                = [result[1] for result in results]
    confidences             = [result[2][0][2] for result in results]
    lifts                   = [result[2][0][3] for result in results]
    return list(zip(left_hand_side_of_rule, right_hand_side_of_rule, supports, confidences, lifts))

resultsinDataFrame = pd.DataFrame(inspect(results), columns = ['Left Hand Side', 'Right Hand Side', 'Support', 'Confidence', 'Lift'])

In [65]:
resultsinDataFrame

         Left Hand Side Right Hand Side   Support  Confidence      Lift
0           light cream         chicken  0.004533    0.290598  4.843951
1  mushroom cream sauce        escalope  0.005733    0.300699  3.790833
2                 pasta        escalope  0.005866    0.372881  4.700812
3         fromage blanc           honey  0.003333    0.245098  5.164271
4         herb & pepper     ground beef  0.015998    0.323450  3.291994
5          tomato sauce     ground beef  0.005333    0.377358  3.840659
6           light cream       olive oil  0.003200    0.205128  3.114710
7     whole wheat pasta       olive oil  0.007999    0.271493  4.122410
8                 pasta          shrimp  0.005066    0.322034  4.506672

## Displaying the results in sorted order by the 'Lift' column (Descending order)

In [67]:
resultsinDataFrame.nlargest(n = 10, columns = 'Lift')

         Left Hand Side Right Hand Side   Support  Confidence      Lift
3         fromage blanc           honey  0.003333    0.245098  5.164271
0           light cream         chicken  0.004533    0.290598  4.843951
2                 pasta        escalope  0.005866    0.372881  4.700812
8                 pasta          shrimp  0.005066    0.322034  4.506672
7     whole wheat pasta       olive oil  0.007999    0.271493  4.122410
5          tomato sauce     ground beef  0.005333    0.377358  3.840659
1  mushroom cream sauce        escalope  0.005733    0.300699  3.790833
4         herb & pepper     ground beef  0.015998    0.323450  3.291994
6           light cream       olive oil  0.003200    0.205128  3.114710